### ISSUE TITLE
Why "Runtime error" like this?

### ISSUE THREAD

**Issue by BaccanoEva** [jojonki/BiDAF#7]
When I run the "python main.py --resume ./checkpoints/Epoch-12.model --test 1"
----Test---
  0%|                                                                                                                                 | 0/528 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 234, in <module>
    test(model, test_data)
  File "main.py", line 186, in test
    p1, p2 = model(c, cc, q, cq)
  File "/Users/liuyancen/anaconda/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liuyancen/Desktop/NLP/BiDAF/layers/attention_net.py", line 50, in forward
    embd_context = self.build_contextual_embd(ctx_c, ctx_w)     # (N, T, 2d)
  File "/Users/liuyancen/Desktop/NLP/BiDAF/layers/attention_net.py", line 31, in build_contextual_embd
    char_embd = self.char_embd_net(x_c) # (N, seq_len, embd_size)
  File "/Users/liuyancen/anaconda/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liuyancen/Desktop/NLP/BiDAF/layers/char_embedding.py", line 35, in forward
    x = [F.relu(conv(x)) for conv in self.conv] # (N, Cout, seq_len, c_embd_size-filter_w+1). stride == 1
  File "/Users/liuyancen/Desktop/NLP/BiDAF/layers/char_embedding.py", line 35, in <listcomp>
    x = [F.relu(conv(x)) for conv in self.conv] # (N, Cout, seq_len, c_embd_size-filter_w+1). stride == 1
  File "/Users/liuyancen/anaconda/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liuyancen/anaconda/envs/python36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/Users/liuyancen/anaconda/envs/python36/lib/python3.6/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (1x161x1x8). Calculated output size: (100x161x-3x-15). Output size is too small at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/THNN/generic/VolumetricConvolutionMM.c:65

How to fix it?

**Comment by jojonki** [comment]
@BaccanoEva Thank you for your report! I am not sure about the error. I will try it at master.

**Comment by jojonki** [comment]
Although I checked on 61af8b1, I could test it without errors.

1. `python main.py`
2. I stopped the training after the first checkpoint, e.g. one epoch.
2. `python main.py --resume ./checkpoints/Epoch-0.model --test 1`

DId you modify the code? If so, I could not imagine the error reasons.

**Comment by BaccanoEva** [comment]
What is your python version? And tensorflow version? Maybe it's the running environment.

**Comment by jojonki** [comment]
I don't use Tensorflow. I recently updated pytorch version. But I mainly developed this project on pytorch 0.3. So it is probably still working on 0.3.
- python 3.6.3
- PyTorch 0.4.0a0+63ac363

**Comment by BaccanoEva** [comment]
Thanks, I will try.

**Comment by BaccanoEva** [comment]
Solved. Thanks!
