### ISSUE TITLE
Getting error on windows 10

### ISSUE THREAD

**Issue by titusfx** [jojonki/BiDAF#9]
Hi, im trying to testing o window 10 and now I'm getting the follow error when I execute "python main.py" :

----
n_train 87599
n_test 10570
ctx_maxlen 3706
vocab_size_w: 75807
vocab_size_c: 212
ctx_sent_maxlen: 866
query_sent_maxlen: 60
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    glove_embd_w = torch.from_numpy(load_glove_weights('./dataset', args.w_embd_size, len(w2i), w2i)).type(torch.FloatTensor)
  File "C:\Users\myuserName\BiDAF\process_data.py", line 109, in load_glove_weights
    for line in f:
  File "C:\Users\myuserName\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2776: character maps to <undefined>

Thanks

**Comment by titusfx** [comment]
I found the solution. In the file process_data, I change all instance of `with open( ... ) ... ` to `with open( ... , encoding='utf-8') `.

I'm getting other error now ...
